# Input data for the GRand canonical Interface Predictor (GRIP). Format is YAML.
# UNITS: Length [=] Angstrom, Temperature [=] Kelvin.
# See the utils/ folder for a visual definition of some parameters.

# Parameters for the sampling algorithm
algo:
    dir_struct: 'best'      # Folder to store all output structures, which is periodically cleaned.
    dir_calcs: 'calc_procs' # Folder to store temporary calculation files for each iteration per core.
    ngrid: 100              # Number of grid points in each dim = ngrid * nprocs to sample for dx, dy.
    frac_min: 0.00          # Minimum fraction of atoms on a plane (0 <= [n] <= 1).
    frac_max: 1.00          # Maximum fraction of atoms on a plane. Set both to 1.0 for gamma surface.
    gb_gap: 0.3             # Initial gap between upper and lower slabs prior to MD/relaxation.
    perturb_u: 0.0          # Maximum random perturbation distance of atoms in upper GB region.
    perturb_l: 0.0          # Maximum random perturbation distance of atoms in lower GB region.
    gb_thick: 10            # Thickness of GB region on either side of interface where atoms can move.
    pad: 10                 # Extra padding on top of gb_thick that are allowed during relaxation for energy calculations.
    vacuum: 1               # Vacuum to add on top of the bicrystal for MD; less is needed for s boundary.

    inter_p: 0.0            # Probability of swapping with interstitial sites. [0.0, 1.0] = [Never, Always].
    inter_s: 'Ti'           # Species of atom to insert into the GB.
    inter_n: 2              # Number of GB interstitial sites to swap with atoms in GB region.
    inter_t: 1.5            # Thickness of region on either side of the GB to search for interstitial positions.
    inter_u: False          # Only choose unique interstitial sites.
    inter_r: True           # True = randomly choose sites to insert/swap; False = choose by largest volume.
    inter_w: 2              # How to swap: 1 = only subs, 2 = only inter, 3 = uniform, 4 = mostly subs, 5 = mostly inter.

    MD_run: 0.95            # Probability of running MD simulation before relaxing. [0.0, 1.0] = [Never, Always].
    Tmin: 300               # Temperature lower bound for MD simulation. Min ~0.3 Tm.
    Tmax: 1100              # Temperature upper bound, vary in multiple of 100s. Max ~0.9 Tm.
    MD_min:   5000          # Min steps for MD simulation.
    MD_max: 300000          # Max steps for MD simulation.
    var_steps: 2            # 0 = Min steps only; 1 = linear sample; 2 = exponential sample number of MD steps.

    lammps_bin: '/g/g16/chen120/bin/lammps_serial'     # Absolute path to [serial] LAMMPS binary or shell command.
    Emult: 2                # Maximum energy threshold * Egb_min to keep; at least 1.0.
    nruns: 0                # Number of iterations in total (on each processor). Set 0 for infinite loop.
    clear_freq: 20          # Number of iterations before clearing duplicates. Set 0 to never clear.
    max_files:   0          # Number of total structures to save (for limited disk space). Set 0 for no limit.


# Parameters for the material, may be potential dependent
struct:
    user: False             # True: read existing cells (POSCAR_*), False: generate w/ ase.
    cutoff: 35              # Max height to cut slabs if user=False to speed up calcs. Set to 0 to ignore.
    write: True             # Write each individual slab to POSCAR_*
    size_min: [1, 1, 1]     # Minimum replications in [x, y, z] to create supercells.
    size_max: [2, 3, 15]    # Maximum replications in [x, y, z] to create supercells. z is not used if user=True.
    reps: 2                 # Sample replications (1) exactly, (2) uniform, (3) weighted smaller, (4) weighted larger.

    # Basic info - potential dependent!
    upper_dirs: [ [5, 2, -7, 0], [0, 0, 0, -1], [-3, 4, -1, 0] ]    # Ti(31-40) tilt
    lower_dirs: [ [7, -2, -5, 0], [0, 0, 0, -1], [-1, 4, -3, 0] ]
    symbol: 'Ti'            # Chemical formula
    crystal: 'hcp'          # fcc, bcc, hcp, or dc
    mass: 47.867            # Atomic mass
    # HENNIG
    a: 2.9305               # a lattice constant at 0K; NOTE!! potential dependent, provide to 4 decimal places.
    c: 4.6783               # c lattice constant at 0K; used for hcp only, ignored for others.
    dlat: 0.703883          # Minimal normal component of lattice vector to calculate Nplane. Required if user=True. Set 0 to ignore.
    Ecoh: -4.8312           # Energy per atom in bulk; NOTE!! potential dependent, provide to 4 decimal places.
    pair_style: 'meam/spline'                                       # pair_style for LAMMPS
    pair_coeff: '* * /g/g16/chen120/lammps/pots/Ti.meam.spline Ti'  # pair_coeff for LAMMPS
    # ZOPE
    #a: 2.9527              # a lattice constant at 0K; NOTE!! potential dependent, provide to 4 decimal places.
    #c: 4.6808              # c lattice constant at 0K; used for hcp only, ignored for others.
    #dlat: 0.0              # Minimal normal component of lattice vector to calculate Nplane. Required if user=True. Set 0 to ignore.
    #Ecoh: -4.8500          # Energy per atom in bulk; NOTE!! potential dependent, provide to 4 decimal places.
    #pair_style: 'eam/alloy'                                         # pair_style for LAMMPS
    #pair_coeff: '* * /g/g16/chen120/lammps/pots/TiAl.eam.alloy Ti'  # pair_coeff for LAMMPS

